### ISSUE TITLE
Config files

### ISSUE THREAD

**Issue by ludiazv** [mmstick/cargo-deb#128]
Thanks for this tool.
I have a question on what would be the proper way to manage configfiles with this crate. If I put a config file in the asset section. In case of package update the config file will get overwritten? This will erase users configuration  made between updates. In principle .debs have stadard way to check and handle this problem. But how it can be used with cargo-deb?

Thanks,

**Comment by kornelski** [comment]
How does the deb format handle this?

**Comment by ludiazv** [comment]
check this small guide: https://blog.serverdensity.com/how-to-create-a-debian-deb-package/
It seems that debian packages has this specific entity called conffiles to deal with this cases.

**Comment by kornelski** [comment]
ok, that seems relatively simple - a list of paths in `conffiles` control file.

I think for cargo deb this could be a new metadata key, like:

```toml
[package.metadata.deb]
config-files = [
   "/etc/foo/bar.conf"
]
```

or an extra flag in assets:

```toml
[package.metadata.deb]
assets = [
    ["templates/bar.conf", "/etc/foo/bar.conf", "644", "config-file"],
```

What do you think?
