### ISSUE TITLE
[feature-request] Introduce a --target aware $target for assets

### ISSUE THREAD

**Issue by MattesWhite** [mmstick/cargo-deb#148]
### Use-Case

I build deb-packages for different targets (amd64, Raspberry Pi Zero and Pi 3). For the Pi-targets I cross-compile on my local machine. Accordingly, the binaries are in the sub-folders `target/arm-unknown-linux-gnueabihf/release/` and `target/armv7-unknown-linux-gnueabihf/release/`.
To include the correct binary (besides other documents) I use variants:
```toml
[package.metadata.deb]
maintainer-scripts = "deb-scripts/"
section = "utility"
depends = "$auto"
assets = [
    ["target/release/my-adapter", "usr/bin/",  "755"],
    ["static/*", "usr/share/my-adapter/static/", "644"]
]

[package.metadata.deb.variants.pi3]
assets = [
    ["target/armv7-unknown-linux-gnueabihf/release/my-adapter", "usr/bin/",  "755"],
    ["static/*", "usr/share/my-adapter/static/", "644"]
]

[package.metadata.deb.variants.pi0]
assets = [
    ["target/arm-unknown-linux-gnueabihf/release/my-adapter", "usr/bin/",  "755"],
    ["static/*", "usr/share/my-adapter/static/", "644"]
]
```

Now to build the package for the Raspberry Pi3 I use:

```
cargo deb --target=armv7-unknown-linux-gnueabihf --variant=pi3
```

This all seems a little bit redundant to me.

### Proposal

I propose to introduce a variable `$target` that resolves differently based on the `--target` option of `cargo deb`, e.g. when invoking `$> cargo deb --target=armv7-unknown-linux-gnueabihf` `$target`would resolve to `target/armv7-unknown-linux-gnueabihf`. This way I could remove the variants from my example:

```toml
[package.metadata.deb]
maintainer-scripts = "deb-scripts/"
section = "utility"
depends = "$auto"
assets = [
    ["$target/release/my-adapter", "usr/bin/",  "755"],
    ["static/*", "usr/share/my-adapter/static/", "644"]
]
```

I know this would result in overriding the packages as both Raspberry Pis result in an `_armhf` package. However, this feels more of a problem of mine as of `cargo deb`.
