### ISSUE TITLE
Use a custom copyright/license file without adding auto-generated lines

### ISSUE THREAD

**Issue by filips123** [mmstick/cargo-deb#187]
I created a custom copyright file that complies with [`debian/copyright` file specification](https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/) and I would like to package it into a DEB archive.

If I just add `license-file = ["debian/copyright", "0"]` to `Cargo.toml`, the file will be packed into an archive, but `cargo-deb` will add [auto-generated lines](https://github.com/mmstick/cargo-deb/blob/8c965d43b88d0de54cc81c0eef8b6a094d43523d/src/data.rs#L41-L48) at the start of file, causing duplicated or possibly incorrect data.

Maybe there could be an additional option in `license-file` to prevent adding auto-generated lines to the copyright/license file?

**Comment by kornelski** [comment]
These lines are not at the start of the license-file. They're just other fields of the control file.

**Comment by kornelski** [comment]
The assumption for `license-file` is that it's a plain file used for Cargo. 

I suppose cargo-deb could try being smart about this and see if the file already uses Debian's syntax, and not add its fields if it does.

**Comment by filips123** [comment]
Considering that `license-file` inside `[package.metadata.deb]` section already uses a different format (array with filename and numbers of lines to skip) than package-level `license-file` (just string filename), could there be another array element to tell cargo-deb to now add any fields?

For example:

```toml
# Standard Cargo.toml stuff
# ...

[package.metadata.deb]
license-file = ["debian/copyright", "0", true]
# So this means debian/copyright filename, skip zero lines, and it is already Debian-formatted file so don't add any new fields
```
